//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS_BankingSys.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.UserDepartments = new HashSet<UserDepartment>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<UserDepartment> UserDepartments { get; set; }
    }
}
