//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS_BankingSys.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        public int id { get; set; }
        public int accountNumber { get; set; }
        public System.DateTimeOffset statementStart { get; set; }
        public System.DateTimeOffset statementEnd { get; set; }
        public double endingBalance { get; set; }
        public System.DateTimeOffset creationDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
