//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS_BankingSys.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDepartment
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int departmentId { get; set; }
        public int isActive { get; set; }
        public System.DateTimeOffset creationTime { get; set; }
        public System.DateTimeOffset modificationTime { get; set; }
        public System.DateTimeOffset deletionTime { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
    }
}
