//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSBank.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int id { get; set; }
        public int cardNumber { get; set; }
        public int accountNumber { get; set; }
        public int cvv { get; set; }
        public int experationDate { get; set; }
        public string firstName { get; set; }
        public string middleInitial { get; set; }
        public string lastName { get; set; }
        public bool isCredit { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
