//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSBank.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.SecurityQuestions = new HashSet<SecurityQuestion>();
        }
    
        public int id { get; set; }
        public string question1 { get; set; }
    
        public virtual ICollection<SecurityQuestion> SecurityQuestions { get; set; }
    }
}
