//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSBank.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int id { get; set; }
        public int messageType { get; set; }
        public string context { get; set; }
        public string ip { get; set; }
        public string component { get; set; }
        public string process { get; set; }
        public string message { get; set; }
        public string time { get; set; }
    }
}
