//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSBank.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Accounts = new HashSet<Account>();
            this.SecurityQuestions = new HashSet<SecurityQuestion>();
        }
    
        public int id { get; set; }
        public int roleId { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string salt { get; set; }
        public string hash { get; set; }
        public string phone { get; set; }
        public string organization { get; set; }
        public bool isActive { get; set; }
        public System.DateTimeOffset creationTime { get; set; }
        public System.DateTimeOffset modificationTime { get; set; }
        public System.DateTimeOffset deletionTime { get; set; }
        public System.DateTimeOffset lockoutTime { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<SecurityQuestion> SecurityQuestions { get; set; }
        public virtual UserDepartment UserDepartment { get; set; }
    }
}
