// <auto-generated />
namespace SoftSec_BankingApp_Se7en.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AccountNumberChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountNumberChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201310180325078_AccountNumberChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
